pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=Build
      - status-success=Test
      - status-success=Lint
    actions:
      merge:
        method: squash
