name-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: '🚀 Features'
    labels: ['feat', 'feature']
  - title: '🐛 Fixes'
    labels: ['fix', 'bugfix', 'bug']
  - title: '🧰 Maintenance'
    labels: ['chore', 'maintenance']
  - title: '🧪 Tests'
    labels: ['test']
  - title: '📚 Documentation'
    labels: ['docs']
