name: AI Standards Validate and Generate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML jsonschema
      - name: Validate files
        run: |
          python scripts/validate.py
      - name: Generate runtime instructions
        run: |
          python scripts/generate_instructions.py
      - name: Upload runtime artifacts
        uses: actions/upload-artifact@v4
        with:
          name: copilot-runtime
          path: .github/copilot/runtime/
