name: Security Scan
on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:
jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install safety
      - name: Scan
        run: |
          safety check --full-report || true
